title: sandinbrain
email: sanjotbains@gmail.com
description: >-
  Blog about whatever damned thing has cut my finger this time.

baseurl: ""
url: "http://www.sandinbrain.com"
twitter_username: sandinbrain
github_username: sanjotbains

# Switch from local gem to remote_theme so github-pages
# still works but we can override all layouts/includes/sass locally.
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Default post_class for posts that don't specify one
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      post_class: general
